<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CreacionFeatures.Domain\CreacionFeatures.Domain.csproj" />
    <ProjectReference Include="..\CreacionFeatures.Application\CreacionFeatures.Application.csproj" />
  </ItemGroup>
</Project>
